### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by Walden134** [Emmanuel-R8/Time_Series_Transformers#1]
hi，I just started learning machine learning，how can I solve this error in use?

**Comment by Walden134** [comment]
E:\下载\谷歌浏览器 下载\Time_Series_Transformers-master\pytorch_lightning\utilities\distributed.py:22: UserWarning: Unsupported `ReduceOp` for distributed computing.
  warnings.warn(*args, **kwargs)
Neptune is running in offline mode. No data is being logged to Neptune.
Disable offline mode to log your experiments.
NeptuneLogger will work in offline mode
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
E:\下载\谷歌浏览器 下载\Time_Series_Transformers-master\pytorch_lightning\utilities\distributed.py:22: UserWarning: GPU available but not used. Set the --gpus flag when calling the script.
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "E:/下载/谷歌浏览器 下载/Time_Series_Transformers-master/TXL_notebook.py", line 103, in <module>
    transformerxl_trainer.fit(transformerxl_model)
  File "E:\下载\谷歌浏览器 下载\Time_Series_Transformers-master\pytorch_lightning\trainer\trainer.py", line 1030, in fit
    results = self.accelerator_backend.spawn_ddp_children(model)
  File "E:\下载\谷歌浏览器 下载\Time_Series_Transformers-master\pytorch_lightning\accelerator_backends\ddp_backend.py", line 90, in spawn_ddp_children
    num_gpus = os.environ['CUDA_VISIBLE_DEVICES'].split(',').__len__()
  File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

**Comment by Emmanuel-R8** [comment]
I am not sure. It seems related to having GPUs available. 

I do not have any GPUs on my laptop and have only used TPUs when running on Google Colab, so I never ran into that problem.
